name:  ProgressBar
author:  davidwalsh
current:  1.2
category:  Interface
tags:  [progress,fx,forms,images]
docs:  http://davidwalsh.name/js/progressbar
demo:  http://davidwalsh.name/js/progressbar

sources:
  - "Source/ProgressBar.js"
